version: '3.7'
services:
  app1:
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        JAR_FILE: "build/libs/app1*.jar"
    ports:
      - "8100:8080"
    environment:
      PROFILE: dev
      PORT: 8080
    container_name: app1